server:
  port: 8080
  servlet:
    context-path: "/checkout-api"

# expose metrics endpoint locally only /rest/external/*
management:
  endpoints:
    web:
      exposure:
        include: metrics,health
    jmx:
      exposure:
        include: metrics
#Logs
logback.logs.folder: /var/log/checkout-api

# JACKSON #
spring:
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
      INDENT_OUTPUT: true
  jpa:
    properties:
      hibernate:
        dialect: com.adrian.rebollo.types.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
        ddl-auto: validate
    generate-ddl: true
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  flyway:
    schemas: public
    url: jdbc:postgresql://${DB_HOST}/${POSTGRES_DB}
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    enabled: true
    locations: classpath:db
    baselineOnMigrate: true
  mvc:
    date-format: ddMMyyyy

pagination:
  products:
    chunksize: 10
  orders:
    chunksize: 100

#Platform Context#
logging.level.org.springframework.security: DEBUG
logging.level.io.swagger.api: DEBUG
logging.level.io.swagger.models.parameters.AbstractSerializableParameter: ERROR

#--PLATFORM--#
spring.application.name: Checkout api- Adrian Rebollo